import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PC
 */
public class administrator extends javax.swing.JFrame {

    /**
     * Creates new form administrator
     */
    public administrator() {
        initComponents();
                            try {
            //Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/project", "java", "java");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/java", "root", "");
        } catch (SQLException ex) { 
          Logger.getLogger(cancel_rent.class.getName()).log(Level.SEVERE, null, ex);
      } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        show_database = new javax.swing.JButton();
        control_database = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(640, 390));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Pristina", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Administrator Interface ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 30, 326, 44);

        show_database.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        show_database.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-show-property-26.png"))); // NOI18N
        show_database.setText("see your database ");
        show_database.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_databaseActionPerformed(evt);
            }
        });
        getContentPane().add(show_database);
        show_database.setBounds(10, 260, 210, 30);

        control_database.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        control_database.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-control-panel-32.png"))); // NOI18N
        control_database.setText("control your database");
        control_database.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                control_databaseActionPerformed(evt);
            }
        });
        getContentPane().add(control_database);
        control_database.setBounds(230, 260, 250, 30);

        logout.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-logout-rounded-down-26.png"))); // NOI18N
        logout.setText("logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(490, 260, 120, 30);

        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-password-30.png"))); // NOI18N
        jButton1.setText("change your password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 300, 250, 39);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Toyotarentacarfleet1-620x360-1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 620, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void show_databaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_databaseActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        new administrator_show_database().setVisible(true);
    }//GEN-LAST:event_show_databaseActionPerformed

    private void control_databaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_control_databaseActionPerformed
        // TODO add your handling code here:
              this.setVisible(false);
   new administrator_control_database().setVisible(true);
    }//GEN-LAST:event_control_databaseActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
               this.setVisible(false);
new login().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new change_password().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new administrator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton control_database;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logout;
    private javax.swing.JButton show_database;
    // End of variables declaration//GEN-END:variables
}
