/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author PC
 */
public class insert_customer extends javax.swing.JFrame {
Connection con;
    public insert_customer() {
        initComponents();
            try {
           
           con = DriverManager.getConnection("jdbc:mysql://localhost:3306/java", "root", "");
        } catch (SQLException ex) {
            Logger.getLogger(insert_customer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        mdp = new javax.swing.JPasswordField();
        confirm = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(610, 610));
        getContentPane().setLayout(null);
        getContentPane().add(name);
        name.setBounds(210, 100, 150, 30);

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        getContentPane().add(address);
        address.setBounds(210, 160, 150, 30);

        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        getContentPane().add(phone);
        phone.setBounds(210, 220, 150, 30);

        mdp.setText("jPasswordField1");
        getContentPane().add(mdp);
        mdp.setBounds(210, 280, 150, 30);

        confirm.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        confirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-checked-radio-button-24.png"))); // NOI18N
        confirm.setText("confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        getContentPane().add(confirm);
        confirm.setBounds(250, 480, 140, 33);

        back.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-back-arrow-24.png"))); // NOI18N
        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(50, 480, 140, 33);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setText("name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 100, 56, 20);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setText("address");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 160, 90, 23);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setText("phone");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 220, 63, 23);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel6.setText("password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 280, 99, 23);

        jLabel7.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("insert a customer");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(180, 10, 270, 39);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sans titre(3).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -50, 600, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
try{
// CHEKING CONDITION
test_input input= new test_input();
int length=0;
        
        length+= input.password_length_test(mdp.getText(), 5);
        length+= input.name_length_test(name.getText(), 5);
        length+=input.address_length_test(address.getText(), 10);
        length += input.phone_length_test(phone.getText(), 8); 
            if (length==4)
            {
                 Statement stmt = con.createStatement( );
                                       
                 String SQL1 = "select max(customer_id) from customer ;";
                         
                   
                 
                 ResultSet rs1 = stmt.executeQuery( SQL1 );
                 int r_id = 0;
               
                 while(rs1.next()){
                 r_id=rs1.getInt("MAX(customer_id)")+1;              
                 }
            
            String NAME = name.getText();
            String ADDRESS = address.getText();
            String PHONE = phone.getText();
            String MDP = mdp.getText();
            int count;
            
            String sql = "INSERT INTO CUSTOMER VALUES(?,?,?,?,?)";
            PreparedStatement pstmt;
            pstmt = con.prepareStatement(sql);
            pstmt.setInt(1, r_id);
            pstmt.setString(2, NAME);
            pstmt.setString(3,ADDRESS);
            pstmt.setString(4, PHONE);
            pstmt.setString(5, MDP);
            System.out.println(sql);
            count = pstmt.executeUpdate();
            

            if(count >0)
            //JOptionPane.showMessageDialog(null,"The Employee was added Successfully !");
            JOptionPane.showMessageDialog(this, "The customer was added Successfully !", "Success Message", JOptionPane.INFORMATION_MESSAGE);
            else
            JOptionPane.showMessageDialog(this, "Insert Query Execution Failed", "Execution Alert", JOptionPane.ERROR_MESSAGE);
            }
            
            else
            JOptionPane.showMessageDialog(this, "Failed to Add \nAll Fields are Mandatory", "Execution Alert", JOptionPane.ERROR_MESSAGE);    
        }
        catch (SQLIntegrityConstraintViolationException e) {
            // Duplicate entry
            JOptionPane.showMessageDialog(this, "Failed to Add \nDuplicate ID !", "Execution Alert", JOptionPane.ERROR_MESSAGE);
        }
        catch(SQLException err)
        {
            System.out.println(err.getMessage());
            JOptionPane.showMessageDialog(this, "Insert Query Execution Failed", "Execution Alert", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_confirmActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
 this.setVisible(false);
 new administrator_control_database().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insert_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insert_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insert_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insert_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insert_customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton back;
    private javax.swing.JButton confirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField mdp;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    // End of variables declaration//GEN-END:variables
}
