import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PC
 */
public class update_customer extends javax.swing.JFrame {

 Connection con;
    public update_customer() {
        initComponents();
            try {
           
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/java", "root", "");

    } catch (SQLException ex) {
         Logger.getLogger(update_customer.class.getName()).log(Level.SEVERE, null, ex);
     }}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(620, 620));
        getContentPane().setLayout(null);
        getContentPane().add(id);
        id.setBounds(230, 100, 200, 30);
        getContentPane().add(name);
        name.setBounds(230, 160, 200, 30);
        getContentPane().add(address);
        address.setBounds(230, 220, 200, 30);
        getContentPane().add(phone);
        phone.setBounds(230, 280, 200, 30);

        update.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        update.setText("update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(180, 360, 130, 31);

        back.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-back-arrow-24.png"))); // NOI18N
        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(40, 500, 110, 33);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setText("customer id ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 100, 140, 23);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setText("name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 160, 80, 23);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setText("address");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 220, 110, 23);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setText("phone");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 280, 110, 23);

        jLabel7.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("update a customer");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, 10, 280, 39);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sans titre(3).png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 600, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
try{
test_input input= new test_input();
int length=0;
        length+= input.id_length_test(id.getText(), 8);
        length+= input.name_length_test(name.getText(), 5);
        length+=input.address_length_test(address.getText(), 10);
        length += input.phone_length_test(phone.getText(), 8); 
            if (length==4)
            {
            int ID = Integer.parseInt(id.getText());
            String NAME = name.getText();
            String ADDRESS = address.getText();
            int PHONE = Integer.parseInt(phone.getText());
            int count;
  
            String sql = "UPDATE CUSTOMER SET NAME =?, ADRDESS = ?, PHONE= ?  WHERE Customer_ID = ?";
            PreparedStatement pstmt;     
            pstmt = con.prepareStatement(sql);
            pstmt.setString(1,NAME);
            pstmt.setString(2, ADDRESS);
            pstmt.setInt(3, PHONE);
            pstmt.setInt(4, ID);
            //boolean ret = stmt.execute(sql);
            //if(ret == true)
            //{
            count = pstmt.executeUpdate();
            

            if(count >0)
            JOptionPane.showMessageDialog(this, "The customer record was UPDATED Successfully !", "Success Message", JOptionPane.INFORMATION_MESSAGE);
            else
            JOptionPane.showMessageDialog(this, "No customer record was found with the given ID", "Execution Alert", JOptionPane.ERROR_MESSAGE);
            }
            else
            JOptionPane.showMessageDialog(this, "All Fields MUST be filled", "Execution Alert", JOptionPane.ERROR_MESSAGE);    
        }
        
        catch(SQLException err)
        {
            System.out.println(err.getMessage());
            JOptionPane.showMessageDialog(this, "Update Query Execution Failed", "Execution Alert", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_updateActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
this.setVisible(false);
 new administrator_control_database().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton back;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
